apiVersion: apps/v1
kind: Deployment
metadata:
  name: ion-deployment
  labels:
    app: ion
spec:
   replicas: 2
   selector:
    matchLabels:
     app: ion
   template:
     metadata:
       labels:
         app: ion
     spec:
       containers:
       - name: ion
         image: sirishak9/rion:v1.0
         port:
         - containerPort: 80
